services:
  - type: web
    name: medinexus
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /up
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_LOCALE
        value: fr
      - key: APP_NAME
        value: MediNexus
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: medinexus-db
          property: connectionString
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: BCRYPT_ROUNDS
        value: "12"
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: warning

databases:
  - name: medinexus-db
    plan: free
    ipAllowList: []
